---
title: "1-data-acquisition"
format: html
---
# Data aquisition and setup

## Prerequisites
```{r}
install.packages(c("tidyverse", "data.table", "patchwork", "corrplot", "tensorflow", "keras3", "zoo"))
```


## Dataset downloader using python kaggle
## ```{bash}
## uv run kaggle datasets download -d daniyalatta/top-50-cryptocurrencies-historical2020-2025-1h --unzip
## ```


## Load library
```{r}
library(tidyverse)
library(data.table)
```


## Get a list of all CSV files in the directory and reads each CSV file into the list
```{r}
file_paths <- list.files(path = "50_coins_crypto_1h_data_cryptocompare",
                         pattern = "*.csv",
                         full.names = TRUE)

crypto_data <- file_paths %>%
  set_names(str_remove(basename(.), "USDT_1h.csv")) %>% 
  map(fread)
```


```{r}
if (!dir.exists("data")) {
  dir.create("data")
}

saveRDS(crypto_data, "data/crypto_data.rds")
```


## Yfinance daily tickers
```{r}
install.packages("quantmod")
```
```{r}
getYfinanceData <- function(coin_name){
library(quantmod)

  df <- getSymbols(coin_name, src='yahoo', auto.assign=FALSE)
  names(df) <- tolower(gsub(paste0(coin_name , "."), "", names(df)))
  df$adjusted <- NULL
  return(df)
}

saveRDS(getYfinanceData, "data/getYfinanceData.rds")
```
