project:
  type: website

website:
  title: "Crypto Cast"
  sidebar:
    contents:
      - index.qmd
      - 01-data-acquisition.qmd
      - 02-data-cleaning.qmd
      - 03-exploratory-analysis.qmd
      - 04-modeling.qmd
      - 05-results-summary.qmd
